language: shell

os:
- linux

dist: xenial

before_install:
  - |
    sudo add-apt-repository ppa:duggan/bats
    sudo apt-get update
    sudo apt-get install bats

script:
  bats test.bats

notifications:
  email:
    recipients
    - ronald.bradford+travis@gmail.com
    on_success: always
